### ISSUE TITLE
please upload latest version/bugfix

### ISSUE THREAD

**Issue by Sadrak** [sanbeg/Test-Directory#1]
Hello,

the last fix from commit https://github.com/sanbeg/Test-Directory/commit/0d4cae23efa1c9e53af952c1016fad21b5946d85 is not live (see https://metacpan.org/release/Test-Directory/source/lib/Test/Directory.pm#L122).

The fix is important for everyone who use subfolders.

Please make a new release.

Have a nice day!

**Comment by sanbeg** [comment]
Thanks for the heads up; it looks like a few changes on the master branch didn't make the last release.
